name: Bluesky Multi-Account Reposter

on:
  schedule:
    - cron: "0 */4 * * *"  # elke 4 uur uitvoeren
  workflow_dispatch:        # handmatig starten mogelijk

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Repository ophalen
        uses: actions/checkout@v4

      - name: 🐍 Python instellen
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: ⚙️ Dependencies installeren
        run: |
          pip install atproto

      - name: 🚀 Multi-account autoposter uitvoeren
        env:
          BSKY_USERNAME_BG: ${{ secrets.BSKY_USERNAME_BG }}
          BSKY_PASSWORD_BG: ${{ secrets.BSKY_PASSWORD_BG }}
          BSKY_USERNAME_BF: ${{ secrets.BSKY_USERNAME_BF }}
          BSKY_PASSWORD_BF: ${{ secrets.BSKY_PASSWORD_BF }}
          BSKY_USERNAME_BP: ${{ secrets.BSKY_USERNAME_BP }}
          BSKY_PASSWORD_BP: ${{ secrets.BSKY_PASSWORD_BP }}
          BSKY_USERNAME_NB: ${{ secrets.BSKY_USERNAME_NB }}
          BSKY_PASSWORD_NB: ${{ secrets.BSKY_PASSWORD_NB }}
          BSKY_USERNAME_HB: ${{ secrets.BSKY_USERNAME_HB }}
          BSKY_PASSWORD_HB: ${{ secrets.BSKY_PASSWORD_HB }}
        run: |
          echo "🚀 Start multi-account repost-run..."
          python testcase_multi.py > /dev/null 2>&1 || echo "⚠️ Script afgerond met waarschuwing."
          echo "✅ Multi-account run afgerond."